version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_oneD4_golden
    x q[2]
    x q[4]
    cnot q[2],q[4]
    x q[2]
    x q[4]
