
from openql import openql as ql
import os
import argparse

def circuit(new_scheduler='yes', scheduler='ASAP', uniform_sched= 'no', sched_commute = 'yes', mapper='no', moves='no', maptiebreak='random', initial_placement='no', output_dir_name='compiler_output', measurement=True, log_level='LOG_NOTHING'):
    output_dir = output_dir_name
    ql.initialize()
    ql.set_option('output_dir', output_dir)
    
    ql.set_option('log_level', log_level)
    ql.set_option('use_default_gates', 'no')
    
    ql.set_option('mapper', mapper)
    
    ql.set_option('write_qasm_files', 'yes')
    ql.set_option('write_report_files', 'yes')

    platform  = ql.Platform('mctests', 'test_multi_core_4x4_full.json')
    num_circuits = 1
    num_qubits = 32
    p = ql.Program('grover_q32_1', platform, num_qubits)
    k = ql.Kernel('grover_q32_1', platform, num_qubits)
    k.gate('x', (16,))
    k.gate('x', (0,))
    k.gate('ym90', (0,))
    k.gate('x', (1,))
    k.gate('ym90', (1,))
    k.gate('x', (2,))
    k.gate('ym90', (2,))
    k.gate('x', (3,))
    k.gate('ym90', (3,))
    k.gate('x', (4,))
    k.gate('ym90', (4,))
    k.gate('x', (5,))
    k.gate('ym90', (5,))
    k.gate('x', (6,))
    k.gate('ym90', (6,))
    k.gate('x', (7,))
    k.gate('ym90', (7,))
    k.gate('x', (8,))
    k.gate('ym90', (8,))
    k.gate('x', (9,))
    k.gate('ym90', (9,))
    k.gate('x', (10,))
    k.gate('ym90', (10,))
    k.gate('x', (11,))
    k.gate('ym90', (11,))
    k.gate('x', (12,))
    k.gate('ym90', (12,))
    k.gate('x', (13,))
    k.gate('ym90', (13,))
    k.gate('x', (14,))
    k.gate('ym90', (14,))
    k.gate('x', (15,))
    k.gate('ym90', (15,))
    k.gate('x', (16,))
    k.gate('ym90', (16,))
    k.gate('x', (0,))
    k.gate('x', (1,))
    k.gate('x', (2,))
    k.gate('x', (3,))
    k.gate('x', (4,))
    k.gate('x', (5,))
    k.gate('x', (6,))
    k.gate('x', (7,))
    k.gate('x', (8,))
    k.gate('x', (9,))
    k.gate('x', (10,))
    k.gate('x', (11,))
    k.gate('x', (12,))
    k.gate('x', (13,))
    k.gate('x', (14,))
    k.gate('x', (15,))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (1,))
    k.gate('t', (17,))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (0, 1))
    k.gate('tdag', (1,))
    k.gate('t', (0,))
    k.gate('cnot', (0, 1))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (17,))
    k.gate('t', (18,))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (2, 17))
    k.gate('tdag', (17,))
    k.gate('t', (2,))
    k.gate('cnot', (2, 17))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (18,))
    k.gate('t', (19,))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (3, 18))
    k.gate('tdag', (18,))
    k.gate('t', (3,))
    k.gate('cnot', (3, 18))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (19,))
    k.gate('t', (20,))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (4, 19))
    k.gate('tdag', (19,))
    k.gate('t', (4,))
    k.gate('cnot', (4, 19))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (20,))
    k.gate('t', (21,))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (5, 20))
    k.gate('tdag', (20,))
    k.gate('t', (5,))
    k.gate('cnot', (5, 20))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (21,))
    k.gate('t', (22,))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (6, 21))
    k.gate('tdag', (21,))
    k.gate('t', (6,))
    k.gate('cnot', (6, 21))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (22,))
    k.gate('t', (23,))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (7, 22))
    k.gate('tdag', (22,))
    k.gate('t', (7,))
    k.gate('cnot', (7, 22))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (23,))
    k.gate('t', (24,))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (8, 23))
    k.gate('tdag', (23,))
    k.gate('t', (8,))
    k.gate('cnot', (8, 23))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (24,))
    k.gate('t', (25,))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (9, 24))
    k.gate('tdag', (24,))
    k.gate('t', (9,))
    k.gate('cnot', (9, 24))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (25,))
    k.gate('t', (26,))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (10, 25))
    k.gate('tdag', (25,))
    k.gate('t', (10,))
    k.gate('cnot', (10, 25))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (26,))
    k.gate('t', (27,))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (11, 26))
    k.gate('tdag', (26,))
    k.gate('t', (11,))
    k.gate('cnot', (11, 26))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (27,))
    k.gate('t', (28,))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (12, 27))
    k.gate('tdag', (27,))
    k.gate('t', (12,))
    k.gate('cnot', (12, 27))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (28,))
    k.gate('t', (29,))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (13, 28))
    k.gate('tdag', (28,))
    k.gate('t', (13,))
    k.gate('cnot', (13, 28))
    k.gate('x', (30,))
    k.gate('ym90', (30,))
    k.gate('cnot', (29, 30))
    k.gate('tdag', (30,))
    k.gate('cnot', (14, 30))
    k.gate('t', (30,))
    k.gate('cnot', (29, 30))
    k.gate('tdag', (30,))
    k.gate('cnot', (14, 30))
    k.gate('t', (29,))
    k.gate('t', (30,))
    k.gate('x', (30,))
    k.gate('ym90', (30,))
    k.gate('cnot', (14, 29))
    k.gate('tdag', (29,))
    k.gate('t', (14,))
    k.gate('cnot', (14, 29))
    k.gate('x', (16,))
    k.gate('ym90', (16,))
    k.gate('cnot', (15, 16))
    k.gate('tdag', (16,))
    k.gate('cnot', (30, 16))
    k.gate('t', (16,))
    k.gate('cnot', (15, 16))
    k.gate('tdag', (16,))
    k.gate('cnot', (30, 16))
    k.gate('t', (15,))
    k.gate('t', (16,))
    k.gate('x', (16,))
    k.gate('ym90', (16,))
    k.gate('cnot', (30, 15))
    k.gate('tdag', (15,))
    k.gate('t', (30,))
    k.gate('cnot', (30, 15))
    k.gate('x', (30,))
    k.gate('ym90', (30,))
    k.gate('cnot', (29, 30))
    k.gate('tdag', (30,))
    k.gate('cnot', (14, 30))
    k.gate('t', (30,))
    k.gate('cnot', (29, 30))
    k.gate('tdag', (30,))
    k.gate('cnot', (14, 30))
    k.gate('t', (29,))
    k.gate('t', (30,))
    k.gate('x', (30,))
    k.gate('ym90', (30,))
    k.gate('cnot', (14, 29))
    k.gate('tdag', (29,))
    k.gate('t', (14,))
    k.gate('cnot', (14, 29))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (28,))
    k.gate('t', (29,))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (13, 28))
    k.gate('tdag', (28,))
    k.gate('t', (13,))
    k.gate('cnot', (13, 28))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (27,))
    k.gate('t', (28,))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (12, 27))
    k.gate('tdag', (27,))
    k.gate('t', (12,))
    k.gate('cnot', (12, 27))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (26,))
    k.gate('t', (27,))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (11, 26))
    k.gate('tdag', (26,))
    k.gate('t', (11,))
    k.gate('cnot', (11, 26))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (25,))
    k.gate('t', (26,))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (10, 25))
    k.gate('tdag', (25,))
    k.gate('t', (10,))
    k.gate('cnot', (10, 25))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (24,))
    k.gate('t', (25,))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (9, 24))
    k.gate('tdag', (24,))
    k.gate('t', (9,))
    k.gate('cnot', (9, 24))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (23,))
    k.gate('t', (24,))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (8, 23))
    k.gate('tdag', (23,))
    k.gate('t', (8,))
    k.gate('cnot', (8, 23))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (22,))
    k.gate('t', (23,))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (7, 22))
    k.gate('tdag', (22,))
    k.gate('t', (7,))
    k.gate('cnot', (7, 22))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (21,))
    k.gate('t', (22,))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (6, 21))
    k.gate('tdag', (21,))
    k.gate('t', (6,))
    k.gate('cnot', (6, 21))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (20,))
    k.gate('t', (21,))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (5, 20))
    k.gate('tdag', (20,))
    k.gate('t', (5,))
    k.gate('cnot', (5, 20))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (19,))
    k.gate('t', (20,))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (4, 19))
    k.gate('tdag', (19,))
    k.gate('t', (4,))
    k.gate('cnot', (4, 19))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (18,))
    k.gate('t', (19,))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (3, 18))
    k.gate('tdag', (18,))
    k.gate('t', (3,))
    k.gate('cnot', (3, 18))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (17,))
    k.gate('t', (18,))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (2, 17))
    k.gate('tdag', (17,))
    k.gate('t', (2,))
    k.gate('cnot', (2, 17))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (1,))
    k.gate('t', (17,))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (0, 1))
    k.gate('tdag', (1,))
    k.gate('t', (0,))
    k.gate('cnot', (0, 1))
    k.gate('x', (0,))
    k.gate('x', (1,))
    k.gate('x', (2,))
    k.gate('x', (3,))
    k.gate('x', (4,))
    k.gate('x', (5,))
    k.gate('x', (6,))
    k.gate('x', (7,))
    k.gate('x', (8,))
    k.gate('x', (9,))
    k.gate('x', (10,))
    k.gate('x', (11,))
    k.gate('x', (12,))
    k.gate('x', (13,))
    k.gate('x', (14,))
    k.gate('x', (15,))
    k.gate('x', (0,))
    k.gate('ym90', (0,))
    k.gate('x', (1,))
    k.gate('ym90', (1,))
    k.gate('x', (2,))
    k.gate('ym90', (2,))
    k.gate('x', (3,))
    k.gate('ym90', (3,))
    k.gate('x', (4,))
    k.gate('ym90', (4,))
    k.gate('x', (5,))
    k.gate('ym90', (5,))
    k.gate('x', (6,))
    k.gate('ym90', (6,))
    k.gate('x', (7,))
    k.gate('ym90', (7,))
    k.gate('x', (8,))
    k.gate('ym90', (8,))
    k.gate('x', (9,))
    k.gate('ym90', (9,))
    k.gate('x', (10,))
    k.gate('ym90', (10,))
    k.gate('x', (11,))
    k.gate('ym90', (11,))
    k.gate('x', (12,))
    k.gate('ym90', (12,))
    k.gate('x', (13,))
    k.gate('ym90', (13,))
    k.gate('x', (14,))
    k.gate('ym90', (14,))
    k.gate('x', (15,))
    k.gate('ym90', (15,))
    k.gate('x', (0,))
    k.gate('x', (1,))
    k.gate('x', (2,))
    k.gate('x', (3,))
    k.gate('x', (4,))
    k.gate('x', (5,))
    k.gate('x', (6,))
    k.gate('x', (7,))
    k.gate('x', (8,))
    k.gate('x', (9,))
    k.gate('x', (10,))
    k.gate('x', (11,))
    k.gate('x', (12,))
    k.gate('x', (13,))
    k.gate('x', (14,))
    k.gate('x', (15,))
    k.gate('x', (15,))
    k.gate('ym90', (15,))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (1,))
    k.gate('t', (17,))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (0, 1))
    k.gate('tdag', (1,))
    k.gate('t', (0,))
    k.gate('cnot', (0, 1))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (17,))
    k.gate('t', (18,))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (2, 17))
    k.gate('tdag', (17,))
    k.gate('t', (2,))
    k.gate('cnot', (2, 17))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (18,))
    k.gate('t', (19,))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (3, 18))
    k.gate('tdag', (18,))
    k.gate('t', (3,))
    k.gate('cnot', (3, 18))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (19,))
    k.gate('t', (20,))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (4, 19))
    k.gate('tdag', (19,))
    k.gate('t', (4,))
    k.gate('cnot', (4, 19))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (20,))
    k.gate('t', (21,))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (5, 20))
    k.gate('tdag', (20,))
    k.gate('t', (5,))
    k.gate('cnot', (5, 20))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (21,))
    k.gate('t', (22,))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (6, 21))
    k.gate('tdag', (21,))
    k.gate('t', (6,))
    k.gate('cnot', (6, 21))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (22,))
    k.gate('t', (23,))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (7, 22))
    k.gate('tdag', (22,))
    k.gate('t', (7,))
    k.gate('cnot', (7, 22))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (23,))
    k.gate('t', (24,))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (8, 23))
    k.gate('tdag', (23,))
    k.gate('t', (8,))
    k.gate('cnot', (8, 23))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (24,))
    k.gate('t', (25,))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (9, 24))
    k.gate('tdag', (24,))
    k.gate('t', (9,))
    k.gate('cnot', (9, 24))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (25,))
    k.gate('t', (26,))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (10, 25))
    k.gate('tdag', (25,))
    k.gate('t', (10,))
    k.gate('cnot', (10, 25))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (26,))
    k.gate('t', (27,))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (11, 26))
    k.gate('tdag', (26,))
    k.gate('t', (11,))
    k.gate('cnot', (11, 26))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (27,))
    k.gate('t', (28,))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (12, 27))
    k.gate('tdag', (27,))
    k.gate('t', (12,))
    k.gate('cnot', (12, 27))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (28,))
    k.gate('t', (29,))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (13, 28))
    k.gate('tdag', (28,))
    k.gate('t', (13,))
    k.gate('cnot', (13, 28))
    k.gate('x', (15,))
    k.gate('ym90', (15,))
    k.gate('cnot', (14, 15))
    k.gate('tdag', (15,))
    k.gate('cnot', (29, 15))
    k.gate('t', (15,))
    k.gate('cnot', (14, 15))
    k.gate('tdag', (15,))
    k.gate('cnot', (29, 15))
    k.gate('t', (14,))
    k.gate('t', (15,))
    k.gate('x', (15,))
    k.gate('ym90', (15,))
    k.gate('cnot', (29, 14))
    k.gate('tdag', (14,))
    k.gate('t', (29,))
    k.gate('cnot', (29, 14))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (29,))
    k.gate('cnot', (28, 29))
    k.gate('tdag', (29,))
    k.gate('cnot', (13, 29))
    k.gate('t', (28,))
    k.gate('t', (29,))
    k.gate('x', (29,))
    k.gate('ym90', (29,))
    k.gate('cnot', (13, 28))
    k.gate('tdag', (28,))
    k.gate('t', (13,))
    k.gate('cnot', (13, 28))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (28,))
    k.gate('cnot', (27, 28))
    k.gate('tdag', (28,))
    k.gate('cnot', (12, 28))
    k.gate('t', (27,))
    k.gate('t', (28,))
    k.gate('x', (28,))
    k.gate('ym90', (28,))
    k.gate('cnot', (12, 27))
    k.gate('tdag', (27,))
    k.gate('t', (12,))
    k.gate('cnot', (12, 27))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (27,))
    k.gate('cnot', (26, 27))
    k.gate('tdag', (27,))
    k.gate('cnot', (11, 27))
    k.gate('t', (26,))
    k.gate('t', (27,))
    k.gate('x', (27,))
    k.gate('ym90', (27,))
    k.gate('cnot', (11, 26))
    k.gate('tdag', (26,))
    k.gate('t', (11,))
    k.gate('cnot', (11, 26))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (26,))
    k.gate('cnot', (25, 26))
    k.gate('tdag', (26,))
    k.gate('cnot', (10, 26))
    k.gate('t', (25,))
    k.gate('t', (26,))
    k.gate('x', (26,))
    k.gate('ym90', (26,))
    k.gate('cnot', (10, 25))
    k.gate('tdag', (25,))
    k.gate('t', (10,))
    k.gate('cnot', (10, 25))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (25,))
    k.gate('cnot', (24, 25))
    k.gate('tdag', (25,))
    k.gate('cnot', (9, 25))
    k.gate('t', (24,))
    k.gate('t', (25,))
    k.gate('x', (25,))
    k.gate('ym90', (25,))
    k.gate('cnot', (9, 24))
    k.gate('tdag', (24,))
    k.gate('t', (9,))
    k.gate('cnot', (9, 24))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (24,))
    k.gate('cnot', (23, 24))
    k.gate('tdag', (24,))
    k.gate('cnot', (8, 24))
    k.gate('t', (23,))
    k.gate('t', (24,))
    k.gate('x', (24,))
    k.gate('ym90', (24,))
    k.gate('cnot', (8, 23))
    k.gate('tdag', (23,))
    k.gate('t', (8,))
    k.gate('cnot', (8, 23))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (23,))
    k.gate('cnot', (22, 23))
    k.gate('tdag', (23,))
    k.gate('cnot', (7, 23))
    k.gate('t', (22,))
    k.gate('t', (23,))
    k.gate('x', (23,))
    k.gate('ym90', (23,))
    k.gate('cnot', (7, 22))
    k.gate('tdag', (22,))
    k.gate('t', (7,))
    k.gate('cnot', (7, 22))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (22,))
    k.gate('cnot', (21, 22))
    k.gate('tdag', (22,))
    k.gate('cnot', (6, 22))
    k.gate('t', (21,))
    k.gate('t', (22,))
    k.gate('x', (22,))
    k.gate('ym90', (22,))
    k.gate('cnot', (6, 21))
    k.gate('tdag', (21,))
    k.gate('t', (6,))
    k.gate('cnot', (6, 21))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (21,))
    k.gate('cnot', (20, 21))
    k.gate('tdag', (21,))
    k.gate('cnot', (5, 21))
    k.gate('t', (20,))
    k.gate('t', (21,))
    k.gate('x', (21,))
    k.gate('ym90', (21,))
    k.gate('cnot', (5, 20))
    k.gate('tdag', (20,))
    k.gate('t', (5,))
    k.gate('cnot', (5, 20))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (20,))
    k.gate('cnot', (19, 20))
    k.gate('tdag', (20,))
    k.gate('cnot', (4, 20))
    k.gate('t', (19,))
    k.gate('t', (20,))
    k.gate('x', (20,))
    k.gate('ym90', (20,))
    k.gate('cnot', (4, 19))
    k.gate('tdag', (19,))
    k.gate('t', (4,))
    k.gate('cnot', (4, 19))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (19,))
    k.gate('cnot', (18, 19))
    k.gate('tdag', (19,))
    k.gate('cnot', (3, 19))
    k.gate('t', (18,))
    k.gate('t', (19,))
    k.gate('x', (19,))
    k.gate('ym90', (19,))
    k.gate('cnot', (3, 18))
    k.gate('tdag', (18,))
    k.gate('t', (3,))
    k.gate('cnot', (3, 18))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (18,))
    k.gate('cnot', (17, 18))
    k.gate('tdag', (18,))
    k.gate('cnot', (2, 18))
    k.gate('t', (17,))
    k.gate('t', (18,))
    k.gate('x', (18,))
    k.gate('ym90', (18,))
    k.gate('cnot', (2, 17))
    k.gate('tdag', (17,))
    k.gate('t', (2,))
    k.gate('cnot', (2, 17))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (17,))
    k.gate('cnot', (1, 17))
    k.gate('tdag', (17,))
    k.gate('cnot', (0, 17))
    k.gate('t', (1,))
    k.gate('t', (17,))
    k.gate('x', (17,))
    k.gate('ym90', (17,))
    k.gate('cnot', (0, 1))
    k.gate('tdag', (1,))
    k.gate('t', (0,))
    k.gate('cnot', (0, 1))
    k.gate('x', (15,))
    k.gate('ym90', (15,))
    k.gate('x', (0,))
    k.gate('x', (1,))
    k.gate('x', (2,))
    k.gate('x', (3,))
    k.gate('x', (4,))
    k.gate('x', (5,))
    k.gate('x', (6,))
    k.gate('x', (7,))
    k.gate('x', (8,))
    k.gate('x', (9,))
    k.gate('x', (10,))
    k.gate('x', (11,))
    k.gate('x', (12,))
    k.gate('x', (13,))
    k.gate('x', (14,))
    k.gate('x', (15,))
    k.gate('x', (0,))
    k.gate('ym90', (0,))
    k.gate('x', (1,))
    k.gate('ym90', (1,))
    k.gate('x', (2,))
    k.gate('ym90', (2,))
    k.gate('x', (3,))
    k.gate('ym90', (3,))
    k.gate('x', (4,))
    k.gate('ym90', (4,))
    k.gate('x', (5,))
    k.gate('ym90', (5,))
    k.gate('x', (6,))
    k.gate('ym90', (6,))
    k.gate('x', (7,))
    k.gate('ym90', (7,))
    k.gate('x', (8,))
    k.gate('ym90', (8,))
    k.gate('x', (9,))
    k.gate('ym90', (9,))
    k.gate('x', (10,))
    k.gate('ym90', (10,))
    k.gate('x', (11,))
    k.gate('ym90', (11,))
    k.gate('x', (12,))
    k.gate('ym90', (12,))
    k.gate('x', (13,))
    k.gate('ym90', (13,))
    k.gate('x', (14,))
    k.gate('ym90', (14,))
    k.gate('x', (15,))
    k.gate('ym90', (15,))

    if measurement:
        for q in range(num_qubits):
            k.gate('measure', [q])

    p.add_kernel(k)
    p.compile()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='OpenQL compilation of a Quantum Algorithm')
    parser.add_argument('--new_scheduler', nargs='?', default='yes', help='Scheduler defined by Hans')
    parser.add_argument('--scheduler', nargs='?', default='ASAP', help='Scheduler specification (ASAP (default), ALAP, ...)')
    parser.add_argument('--uniform_sched', nargs='?', default='no', help='Uniform shceduler actication (yes or no)')
    parser.add_argument('--sched_commute', nargs='?', default='yes', help='Permits two-qubit gates to be commutable')
    parser.add_argument('--mapper', nargs='?', default='minextend', help='Mapper specification (base, minextend, minextendrc)')
    parser.add_argument('--moves', nargs='?', default='no', help='Let the use of moves')
    parser.add_argument('--maptiebreak', nargs='?', default='random', help='')
    parser.add_argument('--initial_placement', nargs='?', default='no', help='Initial placement specification (yes or no)')
    parser.add_argument('--out_dir', nargs='?', default='compiler_output', help='Folder name to store the compilation')
    parser.add_argument('--measurement', nargs='?', default=True, help='Add measurement to all the qubits in the end of the algorithm')
    args = parser.parse_args()
    try:
        circuit(args.new_scheduler, args.scheduler, args.uniform_sched, args.sched_commute, args.mapper, args.moves, args.maptiebreak, args.initial_placement, args.out_dir)
    except TypeError:
        print('\nCompiled, but some gate is not defined in the configuration file. \nThe gate will be invoked like it is.')
        raise