# Generated by OpenQL 0.9.0 for program test_measure_available02
version 1.2

pragma @ql.name("test_measure_available02")


.aKernel
    { # start at cycle 0
        measure q[0]
        measure q[2]
    }
    skip 1
