# Generated by OpenQL 0.9.0 for program test_smis_all_bundled
version 1.2

pragma @ql.name("test_smis_all_bundled")


.aKernel
    { # start at cycle 0
        prepz q[0]
        prepz q[1]
        prepz q[2]
        prepz q[3]
        prepz q[4]
        prepz q[5]
        prepz q[6]
    }
    skip 1
    { # start at cycle 2
        x q[0]
        x q[1]
        x q[2]
        x q[3]
        x q[4]
        x q[5]
        x q[6]
    }
    skip 1
