# Generated by OpenQL 0.9.0 for program swap_multi
version 1.2

pragma @ql.name("swap_multi")


.aKernel
    { # start at cycle 0
        x q[0]
        x q[1]
    }
    skip 7
    swap q[0], q[1]
    skip 15
    { # start at cycle 24
        cz q[0], q[2]
        cz q[1], q[4]
    }
    skip 15
