# Generated by OpenQL 0.9.0 for program test_conjugate
version 1.2

pragma @ql.name("test_conjugate")


.kernel_orignal
    x q[0]
    y q[0]
    z q[0]
    h q[0]
    i q[0]
    s q[0]
    t q[0]
    sdag q[0]
    tdag q[0]
    cnot q[0], q[1]
    cz q[1], q[2]
    swap q[2], q[0]
    toffoli q[0], q[1], q[2]

.kernel_conjugate
    toffoli q[0], q[1], q[2]
    swap q[2], q[0]
    cz q[1], q[2]
    cnot q[0], q[1]
    t q[0]
    s q[0]
    tdag q[0]
    sdag q[0]
    i q[0]
    h q[0]
    z q[0]
    y q[0]
    x q[0]
