# Generated by OpenQL 0.9.0 for program test_controlled_two_qubit_gates
version 1.2

pragma @ql.name("test_controlled_two_qubit_gates")


.kernel1
    swap q[0], q[1]
    skip 3

.controlled_kernel1
    cnot q[1], q[0]
    skip 3
    { # start at cycle 4
        cnot q[2], q[0]
        h q[1]
    }
    skip 1
    t q[1]
    skip 1
    { # start at cycle 8
        t q[2]
        tdag q[0]
    }
    skip 1
    cnot q[1], q[0]
    skip 3
    { # start at cycle 14
        cnot q[2], q[1]
        t q[0]
    }
    skip 3
    { # start at cycle 18
        cnot q[2], q[0]
        tdag q[1]
    }
    skip 3
    { # start at cycle 22
        tdag q[0]
        cnot q[2], q[1]
    }
    skip 3
    cnot q[1], q[0]
    skip 3
    { # start at cycle 30
        t q[0]
        h q[1]
    }
    skip 1
    cnot q[1], q[0]
    skip 3
