# Generated by OpenQL 0.9.0 for program test_issue179_ALAP
version 1.2

pragma @ql.name("test_issue179_ALAP")


.kernel_issue179_ALAP
    y q[3]
    skip 1
    { # start at cycle 2
        x q[2]
        x q[4]
    }
    skip 1
