# Generated by OpenQL 0.9.0 for program test_measure_busy
version 1.2

pragma @ql.name("test_measure_busy")


.aKernel
    wait 1, q[2]
    { # start at cycle 1
        measure q[0]
        measure q[2]
    }
    skip 1
