package:
  name: openql
  version: "{{ load_setup_py_data().version }}"

source:
  path: ../.

build:
  number: 0
  script_env:
    - NPROCS
    - OPENQL_BUILD_TYPE
    - OPENQL_DISABLE_UNITARY

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools
    - swig
    - cmake
    - flex # [not win]
    - bison # [not win]
    #- winflexbison # [win]
  host:
    - python
    - plumbum
    - delocate # [osx]
  run:
    - python

test:
  imports:
    - openql
  source_files:
    - tests
  requires:
    - pytest
    - numpy
  commands:
    - pytest tests

about:
  home: https://github.com/QuTech-Delft/OpenQL
  license: Apache v2.0
