# Generated by OpenQL 0.9.0 for program basic
version 1.2

pragma @ql.name("basic")


.first_kernel
    prep_z q[0]
    x q[0]
    x90 q[0]
    measure q[0]

.second_kernel
    prep_z q[0]
    x90 q[0]
    cz q[0], q[1]
    x90 q[0]
    measure q[0]
