# Generated by OpenQL 0.11.1 for program test_mapper_one_D4
version 1.2

pragma @ql.name("test_mapper_one_D4")


.kernel_one_D4
    x q[2]
    y q[4]
    { # start at cycle 2
        swap q[2], q[0]
        swap q[4], q[1]
    }
    skip 9
    swap q[1], q[3]
    skip 9
    cnot q[0], q[3]
    skip 3
    { # start at cycle 26
        x q[0]
        y q[3]
    }
