# Generated by OpenQL 0.9.0 for program test_mapper_oneNN
version 1.2

pragma @ql.name("test_mapper_oneNN")


.kernel_oneNN
    ym90 q[5]
    cz q[2], q[5]
    x q[0]
    { # start at cycle 3
        y q[1]
        y90 q[5]
    }
