# Generated by OpenQL 0.9.0 for program test_measure_available01
version 1.2

pragma @ql.name("test_measure_available01")


.aKernel
    { # start at cycle 0
        measure q[0]
        measure q[1]
    }
    skip 1
