# Generated by OpenQL 0.11.1 for program test_mapper_lingling7
version 1.2

pragma @ql.name("test_mapper_lingling7")


.kernel_lingling7
    { # start at cycle 0
        prepz q[8]
        prepz q[7]
    }
    skip 20
    ym90 q[6]
    swap q[6], q[2]
    skip 8
    { # start at cycle 31
        ym90 q[8]
        ym90 q[3]
    }
    { # start at cycle 32
        swap q[8], q[10]
        swap q[6], q[3]
    }
    skip 9
    swap q[8], q[6]
    skip 7
    y90 q[7]
    { # start at cycle 51
        x q[7]
        ym90 q[5]
    }
    cz q[7], q[5]
    skip 1
    swap q[5], q[2]
    skip 2
    ym90 q[4]
    cz q[7], q[4]
    skip 1
    cz q[7], q[10]
    skip 1
    cz q[7], q[10]
    skip 1
    cz q[7], q[5]
    skip 1
    swap q[7], q[10]
    skip 9
    cz q[10], q[8]
    skip 1
    y90 q[10]
    x q[10]
    measure q[10]
    skip 6
    y90 q[5]
    cz q[5], q[7]
    y90 q[4]
    cz q[4], q[7]
    ym90 q[5]
    swap q[5], q[7]
    skip 2
    prepz q[10]
    skip 6
    swap q[5], q[2]
    skip 9
    cz q[0], q[2]
    skip 1
    swap q[2], q[6]
    skip 9
    cz q[3], q[6]
    skip 1
    y90 q[6]
    measure q[6]
    skip 5
    y90 q[10]
    x q[10]
    cz q[10], q[7]
    skip 1
    y90 q[7]
    swap q[7], q[5]
    skip 3
    prepz q[6]
    skip 5
    cz q[10], q[8]
    skip 1
    cz q[10], q[7]
    skip 1
    y90 q[8]
    swap q[10], q[8]
    skip 9
    y90 q[7]
    swap q[10], q[7]
    swap q[5], q[1]
    skip 7
    ym90 q[6]
    cz q[8], q[6]
    swap q[1], q[5]
    cz q[8], q[6]
    skip 1
    swap q[8], q[10]
    skip 6
    cz q[2], q[6]
    skip 1
    ym90 q[2]
    swap q[2], q[5]
    skip 2
    ym90 q[4]
    swap q[7], q[4]
    skip 5
    cz q[3], q[6]
    skip 1
    cz q[8], q[6]
    skip 1
    { # start at cycle 202
        cz q[2], q[6]
        cz q[10], q[7]
    }
    skip 1
    { # start at cycle 204
        y90 q[6]
        y90 q[10]
    }
    x q[10]
    { # start at cycle 206
        measure q[6]
        measure q[10]
    }
    skip 14
    { # start at cycle 221
        prepz q[6]
        prepz q[10]
    }
    skip 21
    y90 q[7]
    swap q[7], q[5]
    skip 7
    ym90 q[6]
    y90 q[10]
    { # start at cycle 254
        cz q[3], q[6]
        x q[10]
        ym90 q[8]
    }
    cz q[10], q[8]
    cz q[2], q[6]
    y90 q[8]
    swap q[8], q[6]
    skip 9
    cz q[10], q[7]
    skip 1
    cz q[10], q[8]
    skip 1
    cz q[10], q[8]
    skip 1
    cz q[5], q[8]
    skip 1
    swap q[10], q[8]
    skip 4
    ym90 q[2]
    swap q[5], q[2]
    skip 3
    y90 q[7]
    swap q[10], q[7]
    skip 3
    ym90 q[3]
    swap q[6], q[3]
    skip 4
    cz q[8], q[5]
    skip 1
    y90 q[5]
    swap q[7], q[5]
    skip 1
    swap q[2], q[0]
    skip 7
    cz q[8], q[6]
    skip 1
    cz q[2], q[5]
    y90 q[8]
    { # start at cycle 314
        x q[8]
        y90 q[5]
    }
    { # start at cycle 315
        measure q[8]
        measure q[5]
    }
    skip 13
    y90 q[6]
