# Generated by OpenQL 0.10.0 for program test_decomposition
version 1.2

pragma @ql.name("test_decomposition")


.aKernel
    rx180 q[0]
    skip 7
    rx180 q[0]
    skip 7
    y q[0]
    skip 3
    { # start at cycle 20
        s q[1]
        ry90 q[3]
    }
    skip 3
    ry90 q[0]
    skip 3
    { # start at cycle 28
        ry90 q[1]
        cz q[2], q[3]
    }
    skip 3
    cz q[0], q[1]
    skip 11
    ry90 q[3]
    skip 3
    ry90 q[1]
    skip 3
