# Generated by OpenQL 0.9.0 for program test_flux_all
version 1.2

pragma @ql.name("test_flux_all")


.kernel_all
    { # start at cycle 0
        x q[0]
        x q[3]
    }
    cz q[0], q[3]
    x q[5]
    cz q[3], q[5]
    x q[1]
    cz q[1], q[3]
    x q[6]
    cz q[3], q[6]
    { # start at cycle 8
        x q[2]
        x q[4]
    }
    { # start at cycle 9
        cz q[2], q[5]
        cz q[3], q[0]
        cz q[4], q[6]
    }
    skip 1
    { # start at cycle 11
        cz q[0], q[2]
        cz q[1], q[4]
        cz q[5], q[3]
    }
    skip 1
    { # start at cycle 13
        cz q[2], q[0]
        cz q[4], q[1]
        cz q[6], q[3]
    }
    skip 1
    { # start at cycle 15
        cz q[3], q[1]
        cz q[5], q[2]
        cz q[6], q[4]
    }
    skip 1
    { # start at cycle 17
        x q[0]
        x q[1]
        x q[2]
        x q[3]
        x q[4]
        x q[5]
        x q[6]
    }
