# Generated by OpenQL 0.9.0 for program test_condex_measure
version 1.2

pragma @ql.name("test_condex_measure")


.kernel_measure
    measure q[0], b[0]
    skip 14
    { # start at cycle 15
        cond (b[0]) measure q[1], b[1]
        cond (!b[0]) measure q[2], b[2]
    }
    skip 14
    { # start at cycle 30
        cond (b[1]) x q[3]
        cond (b[2]) y q[5]
    }
