# Generated by OpenQL 0.9.0 for program test_qwg_2_ALAP
version 1.2

pragma @ql.name("test_qwg_2_ALAP")


.kernel_qwg_2_ALAP
    { # start at cycle 0
        x q[0]
        x q[3]
        x q[5]
    }
    skip 1
    { # start at cycle 2
        x q[1]
        x q[2]
        x q[4]
        x q[6]
        x q[0]
        x q[3]
        x q[5]
    }
    skip 1
    { # start at cycle 4
        y q[1]
        y q[2]
        y q[4]
        y q[6]
    }
    skip 1
    { # start at cycle 6
        y q[0]
        y q[1]
        y q[2]
        y q[3]
        y q[4]
        y q[5]
        y q[6]
    }
    skip 1
