# Generated by OpenQL 0.10.5 for program test_condex_cnot
version 1.2

pragma @ql.name("test_condex_cnot")


.kernel_cnot
    measure q[2], b[2]
    skip 10
    cnot q[0], q[3]
    skip 3
    cond (b[2]) cnot q[0], q[2]
    skip 3
    measure q[2], b[2]
    skip 4
    swap q[3], q[5]
    skip 9
    cond (b[2]) cnot q[0], q[3]
    skip 3
    measure q[2], b[2]
    skip 4
    swap q[3], q[6]
    skip 9
    cond (b[2]) cnot q[0], q[3]
    skip 3
