# Generated by OpenQL 0.9.0 for program test_smis
version 1.2

pragma @ql.name("test_smis")


.aKernel
    { # start at cycle 0
        prepz q[0]
        prepz q[1]
        prepz q[2]
        prepz q[3]
    }
    skip 1
    { # start at cycle 2
        h q[0]
        h q[1]
        x q[2]
        x q[3]
    }
    skip 1
    { # start at cycle 4
        measure q[0]
        measure q[1]
        measure q[2]
        measure q[3]
    }
    skip 1
