# Generated by OpenQL 0.9.0 for program test_skip_yes
version 1.2

pragma @ql.name("test_skip_yes")


.kernel_yes_0
    cnot q[2], q[5]
    skip 2
    { # start at cycle 3
        x q[0]
        y q[1]
    }
