# Generated by OpenQL 0.9.0 for program test_mc_comms
version 1.2

pragma @ql.name("test_mc_comms")


.kernel_comms
    x q[4]
    premove q[4]
    skip 4
    teleportmove q[4], q[2]
    skip 24
    x q[0]
    move q[0], q[1]
    skip 3
    postmove q[2]
    skip 4
    cnot q[1], q[2]
    skip 4
