# Generated by OpenQL 0.9.0 for program test_detuned_2_ALAP
version 1.2

pragma @ql.name("test_detuned_2_ALAP")


.kernel_detuned_2_ALAP
    { # start at cycle 0
        cz q[0], q[2]
        cz q[1], q[4]
    }
    skip 3
    { # start at cycle 4
        x q[3]
        cz q[2], q[5]
        cz q[4], q[6]
    }
    skip 1
    y q[3]
    skip 1
