# Generated by OpenQL 0.9.0 for program test_cnot_mixed_commute
version 1.2

pragma @ql.name("test_cnot_mixed_commute")


.aKernel
    { # start at cycle 0
        cnot q[0], q[2]
        cnot q[0], q[3]
        cnot q[1], q[3]
        cnot q[1], q[4]
    }
    skip 3
    { # start at cycle 4
        cnot q[2], q[0]
        cnot q[2], q[5]
        cnot q[3], q[0]
        cnot q[3], q[1]
        cnot q[3], q[5]
        cnot q[3], q[6]
        cnot q[4], q[1]
        cnot q[4], q[6]
    }
    skip 3
    { # start at cycle 8
        cnot q[5], q[2]
        cnot q[5], q[3]
        cnot q[6], q[3]
        cnot q[6], q[4]
    }
    skip 3
