version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 2

.first_kernel
    prep_z q[0]
    x q[0]
    x90 q[0]
    measure q[0]

.second_kernel
    prep_z q[0]
    x90 q[0]
    cz q[0],q[1]
    x90 q[0]
    measure q[0]
