version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_detuned_ALAP
    { cz q[0],q[2] | cz q[1],q[4] }
    wait 3
    { cz q[0],q[2] | cz q[1],q[4] }
    wait 3
    x q[3]
    wait 1
    y q[3]
    wait 1
