version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    { prepz q[0] | cprepz q[1] }
    wait 1
    { measure q[0] | measure q[1] }
    wait 1
