# Generated by OpenQL 0.10.0 for program test_mc_all_saturate
version 1.2

pragma @ql.name("test_mc_all_saturate")


.kernel_all_saturate
    x q[4]
    cnot q[4], q[5]
    skip 4
    x q[5]
    premove q[5]
    skip 4
    teleportmove q[5], q[3]
    skip 29
    { # start at cycle 42
        premove q[4]
        cnot q[5], q[7]
    }
    skip 4
    { # start at cycle 47
        teleportmove q[4], q[2]
        premove q[5]
    }
    skip 4
    teleportmove q[5], q[14]
    skip 24
    cnot q[4], q[6]
    skip 4
    cnot q[4], q[5]
    skip 4
    cnot q[6], q[5]
    skip 2
    x q[12]
    cnot q[12], q[13]
    preswap q[5]
    skip 3
    x q[13]
    teleportswap q[5], q[13]
    skip 9
    x q[0]
    cnot q[0], q[1]
    skip 4
    x q[1]
    swap q[0], q[1]
    skip 7
    postmove q[3]
    skip 4
    cnot q[0], q[3]
    skip 4
    { # start at cycle 132
        postmove q[2]
        premove q[0]
    }
    skip 4
    { # start at cycle 137
        cnot q[1], q[2]
        teleportmove q[0], q[11]
    }
    skip 4
    premove q[1]
    skip 4
    teleportmove q[1], q[10]
    skip 19
    postmove q[11]
    skip 4
    cnot q[11], q[9]
    skip 3
    x q[8]
    { # start at cycle 177
        cnot q[8], q[9]
        postmove q[10]
        preswap q[11]
    }
    skip 4
    { # start at cycle 182
        cnot q[10], q[8]
        teleportswap q[11], q[4]
    }
    skip 4
    preswap q[8]
    skip 4
    teleportswap q[8], q[3]
    skip 34
    premove q[12]
    skip 4
    teleportmove q[12], q[0]
    skip 4
    premove q[10]
    skip 4
    teleportmove q[10], q[1]
    skip 14
    postmove q[14]
    skip 4
    cnot q[14], q[12]
    skip 4
    preswap q[12]
    skip 4
    { # start at cycle 272
        teleportswap q[12], q[6]
        cnot q[11], q[10]
    }
    skip 1
    postmove q[0]
    skip 2
    { # start at cycle 277
        postswap q[13]
        preswap q[10]
    }
    skip 1
    { # start at cycle 279
        cnot q[2], q[0]
        postmove q[1]
    }
    skip 2
    teleportswap q[10], q[13]
    skip 1
    cnot q[1], q[0]
    skip 4
    cnot q[2], q[1]
    skip 4
    swap q[2], q[0]
    skip 7
    postswap q[3]
    skip 4
    { # start at cycle 307
        postswap q[4]
        cnot q[0], q[3]
    }
    skip 4
    { # start at cycle 312
        cnot q[4], q[5]
        cnot q[3], q[2]
    }
    skip 3
    cnot q[8], q[9]
    { # start at cycle 317
        preswap q[5]
        cnot q[3], q[1]
    }
    skip 3
    x q[9]
    { # start at cycle 322
        teleportswap q[5], q[9]
        cnot q[2], q[1]
    }
    skip 4
    { # start at cycle 327
        cnot q[14], q[15]
        preswap q[1]
    }
    skip 4
    teleportswap q[1], q[15]
    skip 16
    swap q[4], q[7]
    skip 7
    postswap q[6]
    skip 4
    { # start at cycle 362
        cnot q[3], q[0]
        cnot q[4], q[6]
    }
    skip 4
    { # start at cycle 367
        cnot q[2], q[0]
        preswap q[4]
    }
    skip 4
    teleportswap q[4], q[0]
    skip 4
    preswap q[6]
    skip 4
    teleportswap q[6], q[14]
    skip 29
    cnot q[5], q[7]
    skip 4
    { # start at cycle 417
        postswap q[13]
        cnot q[10], q[11]
        preswap q[7]
    }
    skip 4
    { # start at cycle 422
        cnot q[12], q[13]
        teleportswap q[7], q[10]
    }
    skip 4
    { # start at cycle 427
        cnot q[2], q[3]
        preswap q[12]
    }
    skip 4
    teleportswap q[12], q[2]
    skip 11
    postswap q[9]
    skip 4
    cnot q[8], q[9]
    skip 4
    swap q[8], q[9]
    skip 4
    swap q[4], q[5]
    skip 7
    { # start at cycle 467
        preswap q[8]
        postswap q[0]
    }
    skip 4
    { # start at cycle 472
        cnot q[0], q[1]
        teleportswap q[8], q[5]
    }
    skip 4
    preswap q[1]
    skip 4
    teleportswap q[1], q[6]
    skip 34
    preswap q[11]
    skip 4
    teleportswap q[11], q[3]
    skip 4
    preswap q[7]
    skip 4
    teleportswap q[7], q[12]
    skip 34
    { # start at cycle 567
        postswap q[5]
        postswap q[6]
    }
    skip 4
    { # start at cycle 572
        postswap q[3]
        postswap q[2]
        cnot q[0], q[1]
        cnot q[4], q[5]
        preswap q[6]
    }
    skip 4
    { # start at cycle 577
        cnot q[2], q[3]
        preswap q[4]
        teleportswap q[6], q[1]
    }
    skip 4
    teleportswap q[4], q[3]
    skip 44
    { # start at cycle 627
        postswap q[12]
        preswap q[6]
    }
    skip 4
    { # start at cycle 632
        cnot q[12], q[13]
        preswap q[4]
        teleportswap q[6], q[2]
    }
    skip 4
    teleportswap q[4], q[12]
    skip 39
    { # start at cycle 677
        preswap q[8]
        postswap q[3]
    }
    skip 4
    { # start at cycle 682
        postswap q[14]
        preswap q[0]
        teleportswap q[8], q[3]
    }
    skip 4
    teleportswap q[0], q[14]
    skip 26
    swap q[6], q[5]
    skip 7
    { # start at cycle 722
        postswap q[10]
        postswap q[12]
    }
    skip 4
    { # start at cycle 727
        cnot q[9], q[10]
        cnot q[13], q[12]
        cnot q[4], q[5]
    }
    skip 4
    { # start at cycle 732
        cnot q[8], q[9]
        preswap q[13]
        preswap q[5]
    }
    skip 4
    { # start at cycle 737
        teleportswap q[13], q[8]
        teleportswap q[5], q[10]
    }
    skip 39
    postswap q[3]
    skip 4
    { # start at cycle 782
        postswap q[14]
        preswap q[3]
        preswap q[9]
    }
    skip 4
    { # start at cycle 787
        teleportswap q[3], q[14]
        teleportswap q[9], q[7]
    }
    skip 34
    { # start at cycle 822
        postswap q[8]
        postswap q[10]
    }
    skip 1
    swap q[4], q[6]
    skip 2
    cnot q[8], q[10]
    skip 4
    { # start at cycle 832
        preswap q[13]
        preswap q[8]
    }
    skip 3
    postswap q[1]
    { # start at cycle 837
        teleportswap q[13], q[6]
        teleportswap q[8], q[12]
    }
    skip 3
    cnot q[0], q[1]
    skip 4
    swap q[0], q[1]
    skip 7
    postswap q[2]
    skip 4
    cnot q[1], q[2]
    skip 4
    { # start at cycle 864
        cnot q[0], q[2]
        postswap q[7]
    }
    skip 4
    { # start at cycle 869
        swap q[0], q[1]
        cnot q[4], q[7]
    }
    skip 4
    cnot q[4], q[5]
    skip 4
    swap q[4], q[5]
    skip 2
    cnot q[0], q[3]
    skip 4
    { # start at cycle 887
        cnot q[1], q[3]
        postswap q[6]
        postswap q[12]
    }
    skip 4
    { # start at cycle 892
        postswap q[15]
        postswap q[14]
        cnot q[1], q[0]
        cnot q[5], q[6]
        cnot q[12], q[13]
    }
    skip 4
