version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    { cnot q[0],q[2] | cnot q[0],q[3] | cnot q[1],q[3] | cnot q[1],q[4] }
    wait 3
    { cnot q[2],q[0] | cnot q[2],q[5] | cnot q[3],q[0] | cnot q[3],q[1] | cnot q[3],q[5] | cnot q[3],q[6] | cnot q[4],q[1] | cnot q[4],q[6] }
    wait 3
    { cnot q[5],q[2] | cnot q[5],q[3] | cnot q[6],q[3] | cnot q[6],q[4] }
    wait 3
