version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    cnot q[0],q[3]
    wait 3
    cnot q[3],q[5]
    wait 3
    t q[5]
    wait 2
    z q[5]
    wait 1
