# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 1

.aKernel
   prepz q0
   x q0
   y q0
   rx90 q0
   measure q0
.cal0_1
   prepz q0
   measure q0
.cal0_2
   prepz q0
   measure q0
.cal1_1
   prepz q0
   x q0
   measure q0
.cal1_2
   prepz q0
   x q0
   measure q0
