version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    ry90 q[2]
    wait 1
    { ry90 q[0] | rx90 q[2] }
    wait 1
    { measure q[0] | measure q[1] | measure q[2] | measure q[4] }
    wait 1
    { ry90 q[4] | ry90 q[1] }
    wait 1
    { measure q[0] | measure q[1] | measure q[2] | measure q[4] }
    wait 1
    { ry90 q[4] | ry90 q[1] }
    wait 1
