version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_adriaan_ALAP
    prepz q[0]
    wait 1
    x q[0]
    wait 1
    x q[0]
    wait 1
    x q[0]
    wait 1
    { prepz q[2] | x q[0] }
    wait 1
    { x q[0] | rx90 q[2] }
    wait 1
    { x q[0] | rx90 q[2] }
    wait 1
    { x q[0] | rx90 q[2] }
    wait 1
    { x q[0] | rx90 q[2] }
    wait 1
    { x q[0] | rx90 q[2] }
    wait 1
    { x q[0] | rx90 q[2] }
    wait 1
    { measure q[2] | measure q[0] }
    wait 1
