# Generated by OpenQL 0.9.0 for program test_sub_circuit_programs
version 1.2

pragma @ql.name("test_sub_circuit_programs")

var __1: int @ql.temp()

.init_0
    prepz q[0]
    prepz q[1]

.do_somework_1
    foreach (__1 = 2..0) {
        x q[0]
        h q[1]
    }

.do_measurement_2
    measz q[0], b[0]
    measz q[1], b[1]
    measz q[2], b[2]
    measz q[3], b[3]
    measz q[4], b[4]
    measz q[5], b[5]
