# Generated by OpenQL 0.9.0 for program test_barrier
version 1.2

pragma @ql.name("test_barrier")


.aKernel
    { # start at cycle 0
        x q[0]
        x q[1]
    }
    skip 1
    y q[0]
    skip 1
    { # start at cycle 4
        barrier q[0], q[1]
        measure q[0]
        measure q[1]
    }
    skip 1
