# Generated by OpenQL 0.9.0 for program test_mapper_allIP
version 1.2

pragma @ql.name("test_mapper_allIP")


.kernel_allIP
    y90 q[3]
    { # start at cycle 1
        x q[0]
        x q[3]
    }
    cz q[0], q[3]
    skip 1
    { # start at cycle 4
        y90 q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    skip 1
    { # start at cycle 7
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    y90 q[1]
    { # start at cycle 10
        y90 q[3]
        x q[1]
        y90 q[5]
    }
    { # start at cycle 11
        cz q[3], q[1]
        x q[2]
        x q[5]
    }
    cz q[2], q[5]
    x q[3]
    { # start at cycle 14
        cz q[3], q[1]
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    { # start at cycle 16
        y90 q[1]
        ym90 q[3]
    }
    { # start at cycle 17
        cz q[1], q[3]
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    y90 q[3]
    cz q[3], q[5]
    skip 1
    { # start at cycle 22
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 25
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    skip 1
    { # start at cycle 28
        y90 q[5]
        ym90 q[2]
    }
    { # start at cycle 29
        ym90 q[1]
        cz q[5], q[2]
    }
    cz q[3], q[1]
    { # start at cycle 31
        y90 q[2]
        ym90 q[0]
    }
    cz q[2], q[0]
    skip 1
    y90 q[3]
    { # start at cycle 35
        y90 q[0]
        x q[3]
    }
    cz q[0], q[3]
    { # start at cycle 37
        x q[4]
        y90 q[6]
    }
    { # start at cycle 38
        y90 q[3]
        ym90 q[0]
        x q[6]
    }
    { # start at cycle 39
        cz q[3], q[0]
        cz q[4], q[6]
    }
    skip 1
    { # start at cycle 41
        y90 q[0]
        ym90 q[3]
        y90 q[6]
        ym90 q[4]
    }
    { # start at cycle 42
        cz q[0], q[3]
        cz q[6], q[4]
    }
    skip 1
    { # start at cycle 44
        ym90 q[6]
        y90 q[3]
    }
    cz q[3], q[6]
    y90 q[4]
    cz q[4], q[6]
    x q[3]
    cz q[3], q[6]
    skip 1
    { # start at cycle 51
        y90 q[6]
        ym90 q[3]
    }
    cz q[6], q[3]
    skip 1
    { # start at cycle 54
        y90 q[3]
        ym90 q[6]
    }
    cz q[3], q[6]
    skip 1
    ym90 q[5]
    cz q[3], q[5]
    skip 1
    x q[3]
    { # start at cycle 61
        cz q[3], q[5]
        cz q[4], q[1]
    }
    skip 1
    { # start at cycle 63
        y90 q[5]
        ym90 q[3]
        y90 q[1]
        ym90 q[4]
    }
    { # start at cycle 64
        cz q[5], q[3]
        cz q[1], q[4]
    }
    skip 1
    { # start at cycle 66
        y90 q[3]
        ym90 q[1]
    }
    cz q[3], q[1]
    skip 1
    y90 q[4]
    { # start at cycle 70
        ym90 q[5]
        cz q[4], q[1]
    }
    cz q[3], q[5]
    y90 q[1]
    { # start at cycle 73
        x q[1]
        x q[2]
        x q[3]
        y90 q[5]
        y90 q[6]
    }
