version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 17

.kernel_lingling5
    { prepz q[5] | prepz q[6] }
    wait 1
    prepz q[2]
    wait 1
    prepz q[1]
    wait 26
    x q[5]
    y q[5]
    cz q[2],q[5]
    wait 1
    { y90 q[5] | ym90 q[2] }
    cz q[5],q[2]
    wait 1
    { y90 q[2] | ym90 q[0] }
    cz q[2],q[0]
    wait 1
    x q[2]
    y q[2]
    cz q[5],q[2]
    wait 1
    y90 q[6]
    x q[6]
    cz q[6],q[2]
    wait 1
    cz q[6],q[2]
    wait 1
    ym90 q[5]
    cz q[1],q[5]
    y q[3]
    cz q[0],q[3]
    y90 q[5]
    cz q[5],q[2]
    wait 1
    { y90 q[3] | ym90 q[0] }
    cz q[3],q[0]
    x q[2]
    { y90 q[0] | y q[2] }
    cz q[2],q[0]
    wait 1
    y90 q[2]
    x q[2]
    measure q[2]
    wait 14
    measure q[6]
    wait 11
    prepz q[2]
    wait 2
    prepz q[6]
    wait 12
    prepz q[7]
    wait 14
    ym90 q[1]
    cz q[5],q[1]
    wait 1
    ym90 q[5]
    { y90 q[2] | cz q[5],q[1] }
    x q[2]
    cz q[2],q[5]
    wait 1
    { y90 q[1] | ym90 q[5] }
    { y90 q[6] | x q[2] | cz q[1],q[5] }
    { x q[6] | y q[2] }
    cz q[6],q[2]
    wait 1
    cz q[6],q[2]
    ym90 q[3]
    { y q[4] | cz q[0],q[3] }
    { cz q[7],q[4] | y90 q[5] }
    { measure q[6] | cz q[5],q[2] }
    { y90 q[4] | ym90 q[1] }
    { ym90 q[7] | cz q[5],q[1] }
    { cz q[4],q[7] | y90 q[0] }
    ym90 q[5]
    { cz q[0],q[2] | cz q[5],q[7] }
    wait 1
    { y90 q[7] | ym90 q[5] }
    cz q[7],q[5]
    x q[2]
    { y90 q[5] | y q[2] }
    cz q[2],q[5]
    wait 1
    y90 q[2]
    x q[2]
    measure q[2]
    wait 9
    prepz q[6]
    wait 4
    prepz q[2]
    wait 22
    ym90 q[7]
    cz q[5],q[7]
    wait 1
    y90 q[5]
    cz q[5],q[7]
    wait 1
    { y90 q[7] | ym90 q[5] }
    cz q[7],q[5]
    y90 q[2]
    { y90 q[5] | x q[2] }
    cz q[2],q[5]
    wait 1
    x q[2]
    y q[2]
    cz q[0],q[2]
    wait 1
    y90 q[6]
    { ym90 q[7] | x q[6] }
    { cz q[5],q[7] | cz q[6],q[2] }
    wait 1
    y90 q[5]
    { cz q[5],q[7] | cz q[6],q[2] }
    wait 1
    { y90 q[7] | ym90 q[5] }
    { cz q[7],q[5] | ym90 q[0] }
    cz q[0],q[3]
    y90 q[5]
    cz q[5],q[2]
    wait 1
    { y90 q[3] | ym90 q[0] }
    cz q[3],q[0]
    x q[2]
    { y90 q[0] | y q[2] }
    cz q[2],q[0]
    wait 1
    y90 q[2]
    x q[2]
    measure q[2]
    wait 14
    measure q[6]
    wait 13
    prepz q[2]
    prepz q[6]
    wait 29
    ym90 q[3]
    cz q[0],q[3]
    wait 1
    y90 q[0]
    cz q[0],q[3]
    wait 1
    { y90 q[3] | ym90 q[0] }
    cz q[3],q[0]
    wait 1
    { y90 q[0] | ym90 q[3] }
    { cz q[0],q[3] | y90 q[2] }
    x q[2]
    cz q[2],q[0]
    wait 1
    y90 q[0]
    { x q[2] | cz q[0],q[3] }
    y q[2]
    cz q[5],q[2]
    wait 1
    y90 q[6]
    x q[6]
    cz q[6],q[2]
    wait 1
    cz q[6],q[2]
    wait 1
    { y90 q[3] | ym90 q[0] }
    cz q[3],q[0]
    wait 1
    cz q[5],q[1]
    { ym90 q[7] | y90 q[0] }
    { cz q[5],q[7] | cz q[0],q[2] }
    wait 1
    { y90 q[1] | ym90 q[5] }
    cz q[1],q[5]
    x q[2]
    { y90 q[5] | y q[2] }
    cz q[2],q[5]
    wait 1
    y90 q[2]
    x q[2]
    { measure q[6] | measure q[2] }
    wait 8
    ym90 q[3]
    cz q[0],q[3]
    ym90 q[1]
    cz q[5],q[1]
    wait 1
    { y90 q[1] | y90 q[3] | y90 q[5] | y90 q[7] }
