# Generated by OpenQL 0.9.0 for program test_cnot_z_2N_commute
version 1.2

pragma @ql.name("test_cnot_z_2N_commute")


.aKernel
    t q[0]
    skip 2
    z q[0]
    skip 1
    cnot q[3], q[0]
    skip 3
    t q[3]
    skip 2
    z q[3]
    skip 1
