# Generated by OpenQL 0.10.0 for program test_mc_all
version 1.2

pragma @ql.name("test_mc_all")


.kernel_all
    x q[0]
    cnot q[0], q[1]
    skip 4
    x q[1]
    swap q[0], q[1]
    skip 11
    x q[12]
    { # start at cycle 20
        cnot q[12], q[13]
        preswap q[0]
    }
    skip 4
    teleportswap q[0], q[12]
    skip 33
    x q[4]
    cnot q[4], q[5]
    skip 3
    x q[8]
    { # start at cycle 65
        cnot q[8], q[9]
        premove q[4]
    }
    skip 4
    { # start at cycle 70
        premove q[8]
        teleportmove q[4], q[2]
    }
    skip 4
    teleportmove q[8], q[3]
    skip 24
    postmove q[2]
    skip 4
    { # start at cycle 105
        postmove q[3]
        cnot q[1], q[2]
    }
    skip 4
    { # start at cycle 110
        cnot q[2], q[3]
        cnot q[1], q[0]
    }
    skip 4
    { # start at cycle 115
        cnot q[1], q[3]
        cnot q[2], q[0]
    }
    skip 4
    { # start at cycle 120
        cnot q[2], q[1]
        cnot q[3], q[0]
    }
    skip 4
    { # start at cycle 125
        cnot q[3], q[2]
        cnot q[0], q[1]
    }
    skip 4
    { # start at cycle 130
        cnot q[3], q[1]
        cnot q[0], q[2]
    }
    skip 4
    { # start at cycle 135
        postswap q[12]
        cnot q[0], q[3]
    }
    skip 3
    { # start at cycle 139
        x q[5]
        x q[9]
        x q[13]
    }
