version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 12

.kernel1
    x q[0]
    wait 1
    cnot q[0],q[1]
    wait 3

.controlled_kernel1
    toffoli q[2],q[3],q[7]
    wait 7
    toffoli q[4],q[7],q[8]
    wait 7
    toffoli q[5],q[8],q[9]
    wait 7
    toffoli q[6],q[9],q[10]
    wait 7
    cnot q[10],q[0]
    wait 3
    toffoli q[0],q[10],q[1]
    wait 7
    toffoli q[6],q[9],q[10]
    wait 7
    toffoli q[5],q[8],q[9]
    wait 7
    toffoli q[4],q[7],q[8]
    wait 7
    toffoli q[2],q[3],q[7]
    wait 7
