version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 1

.aKernel
    prepz q[0]
    x q[0]
    y q[0]
    rx90 q[0]
    measure q[0]
