version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 2

.akernel
    rz q[1], 1.570796
    ry q[1], -3.141593
    rz q[1], -1.570796
    rz q[0], -0.000000
    cnot q[1],q[0]
    rz q[0], -0.000000
    cnot q[1],q[0]
    rz q[1], 0.000000
    ry q[1], 0.000000
    rz q[1], 0.000000
    ry q[0], 0.000000
    cnot q[1],q[0]
    ry q[0], 0.000000
    cnot q[1],q[0]
    rz q[1], 3.141593
    ry q[1], -1.570796
    rz q[1], -1.570796
    rz q[0], -1.570796
    cnot q[1],q[0]
    rz q[0], -1.570796
    cnot q[1],q[0]
    rz q[1], -3.141593
    ry q[1], -1.570796
    rz q[1], -0.000000
