# Generated by OpenQL 0.9.0 for program test_cqasm_conditions
version 1.2

pragma @ql.name("test_cqasm_conditions")


._0
    measz q[1], breg(1)
    measz q[0], breg(0)
    x q[1]
    cond (breg(1)) z q[1]
    y q[1]
    cond (!breg(1)) z q[1]
    x q[1]
    cond (breg(1)) z q[1]
    cond (breg(1) && breg(0)) x q[1]
    cond (breg(1)) y q[1]
    cond (breg(0)) x q[1]
    cond (breg(1) || breg(0)) z q[1]
    x q[1]
    cond (breg(1)) y q[1]
    z q[1]
    cond (breg(0)) x q[1]
    cond (breg(1) != breg(0)) y q[1]
    cond (!breg(1)) z q[1]
    cond (breg(1)) x q[1]
    cond (!breg(0)) y q[1]
    cond (breg(0)) z q[1]
    cond (!(breg(1) && breg(0))) x q[1]
    cond (!breg(1)) y q[1]
    z q[1]
    cond (!breg(0)) x q[1]
    y q[1]
    cond (!(breg(1) || breg(0))) z q[1]
    cond (!breg(1)) y q[1]
    cond (!breg(0)) x q[1]
    cond (breg(1) == breg(0)) y q[1]
    cond (breg(1)) z q[1]
    cond (!breg(1)) x q[1]
    cond (breg(0)) y q[1]
    cond (!breg(0)) z q[1]
