# Generated by OpenQL 0.9.0 for program test_mapper_allD
version 1.2

pragma @ql.name("test_mapper_allD")


.kernel_allD
    { # start at cycle 0
        x q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    cz q[0], q[3]
    skip 1
    ym90 q[2]
    cz q[0], q[2]
    skip 1
    { # start at cycle 8
        y90 q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    skip 1
    { # start at cycle 11
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    { # start at cycle 14
        y90 q[3]
        ym90 q[6]
    }
    cz q[3], q[6]
    ym90 q[1]
    cz q[3], q[1]
    ym90 q[5]
    cz q[3], q[5]
    y90 q[1]
    { # start at cycle 21
        x q[1]
        ym90 q[3]
    }
    cz q[1], q[3]
    skip 1
    { # start at cycle 24
        ym90 q[4]
        y90 q[5]
    }
    { # start at cycle 25
        cz q[1], q[4]
        cz q[5], q[2]
    }
    skip 1
    { # start at cycle 27
        y90 q[3]
        ym90 q[1]
        y90 q[2]
        ym90 q[5]
    }
    { # start at cycle 28
        cz q[3], q[1]
        cz q[2], q[5]
    }
    skip 1
    { # start at cycle 30
        y90 q[1]
        ym90 q[3]
        y90 q[5]
        ym90 q[2]
    }
    { # start at cycle 31
        cz q[1], q[3]
        cz q[5], q[2]
    }
    skip 1
    { # start at cycle 33
        y90 q[3]
        ym90 q[5]
    }
    cz q[3], q[5]
    skip 1
    cz q[3], q[6]
    skip 1
    y90 q[5]
    x q[5]
    cz q[5], q[2]
    ym90 q[0]
    { # start at cycle 42
        cz q[3], q[0]
        cz q[5], q[2]
    }
    skip 1
    { # start at cycle 44
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    cz q[1], q[4]
    { # start at cycle 47
        y90 q[5]
        ym90 q[2]
    }
    { # start at cycle 48
        ym90 q[1]
        cz q[5], q[2]
    }
    cz q[3], q[1]
    y90 q[2]
    { # start at cycle 51
        cz q[2], q[0]
        ym90 q[5]
    }
    cz q[3], q[5]
    y90 q[0]
    { # start at cycle 54
        x q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    ym90 q[2]
    cz q[0], q[2]
    skip 1
    { # start at cycle 60
        y90 q[2]
        ym90 q[0]
        y90 q[3]
    }
    { # start at cycle 61
        cz q[2], q[0]
        cz q[3], q[6]
    }
    skip 1
    { # start at cycle 63
        y90 q[6]
        ym90 q[3]
    }
    cz q[6], q[3]
    ym90 q[2]
    { # start at cycle 66
        y90 q[0]
        y90 q[3]
        ym90 q[6]
    }
    { # start at cycle 67
        cz q[0], q[2]
        cz q[3], q[6]
    }
    skip 1
    ym90 q[3]
    cz q[0], q[3]
    skip 1
    cz q[0], q[3]
    y90 q[6]
    { # start at cycle 74
        y90 q[3]
        ym90 q[0]
        cz q[6], q[4]
    }
    cz q[3], q[0]
    { # start at cycle 76
        y90 q[4]
        ym90 q[6]
    }
    { # start at cycle 77
        y90 q[0]
        ym90 q[3]
        cz q[4], q[6]
    }
    cz q[0], q[3]
    ym90 q[4]
    y90 q[3]
    { # start at cycle 81
        y90 q[6]
        cz q[3], q[1]
    }
    cz q[6], q[4]
    y90 q[1]
    cz q[1], q[4]
    skip 1
    { # start at cycle 86
        y90 q[4]
        ym90 q[1]
    }
    cz q[4], q[1]
    { # start at cycle 88
        y90 q[2]
        ym90 q[6]
        ym90 q[0]
    }
    { # start at cycle 89
        cz q[3], q[6]
        cz q[2], q[0]
        y90 q[1]
        ym90 q[4]
    }
    cz q[1], q[4]
    { # start at cycle 91
        cz q[2], q[0]
        cz q[3], q[6]
    }
    ym90 q[1]
    { # start at cycle 93
        cz q[2], q[5]
        cz q[3], q[1]
    }
    skip 1
    { # start at cycle 95
        y90 q[0]
        ym90 q[2]
        y90 q[6]
        ym90 q[3]
    }
    { # start at cycle 96
        cz q[0], q[2]
        cz q[6], q[3]
    }
    skip 1
    { # start at cycle 98
        y90 q[2]
        ym90 q[0]
        y90 q[3]
        ym90 q[6]
    }
    { # start at cycle 99
        cz q[2], q[0]
        cz q[3], q[6]
    }
    skip 1
    { # start at cycle 101
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    y90 q[3]
    x q[3]
    cz q[3], q[6]
    ym90 q[0]
    cz q[3], q[0]
    skip 1
    cz q[3], q[5]
    skip 1
    cz q[3], q[1]
    skip 1
    { # start at cycle 114
        y90 q[0]
        ym90 q[3]
        y90 q[6]
    }
    { # start at cycle 115
        cz q[0], q[3]
        cz q[6], q[4]
    }
    skip 1
    { # start at cycle 117
        y90 q[3]
        y90 q[4]
        ym90 q[6]
    }
    { # start at cycle 118
        cz q[4], q[6]
        cz q[3], q[1]
    }
    skip 1
    { # start at cycle 120
        y90 q[6]
        ym90 q[4]
    }
    { # start at cycle 121
        ym90 q[0]
        cz q[6], q[4]
    }
    cz q[3], q[0]
    ym90 q[6]
    cz q[3], q[6]
    skip 1
    { # start at cycle 126
        y90 q[1]
        ym90 q[3]
    }
    cz q[1], q[3]
    skip 1
    { # start at cycle 129
        y90 q[3]
        ym90 q[1]
    }
    cz q[3], q[1]
    y90 q[5]
    { # start at cycle 132
        x q[5]
        ym90 q[2]
        y90 q[0]
        y90 q[1]
        ym90 q[3]
    }
    { # start at cycle 133
        cz q[0], q[2]
        cz q[1], q[4]
        cz q[5], q[3]
    }
    skip 1
    { # start at cycle 135
        y90 q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    skip 1
    { # start at cycle 138
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    y90 q[3]
    cz q[3], q[6]
    ym90 q[1]
    cz q[3], q[1]
    ym90 q[0]
    cz q[3], q[0]
    cz q[5], q[2]
    ym90 q[3]
    { # start at cycle 149
        cz q[5], q[3]
        y90 q[2]
    }
    { # start at cycle 150
        x q[2]
        y90 q[1]
    }
    { # start at cycle 151
        cz q[2], q[0]
        cz q[5], q[3]
        cz q[1], q[4]
    }
    skip 1
    { # start at cycle 153
        y90 q[3]
        ym90 q[5]
        y90 q[4]
        ym90 q[1]
    }
    { # start at cycle 154
        cz q[3], q[5]
        cz q[4], q[1]
        x q[0]
    }
    y q[0]
    { # start at cycle 156
        y90 q[5]
        ym90 q[3]
        y90 q[1]
        ym90 q[4]
    }
    { # start at cycle 157
        cz q[5], q[3]
        cz q[1], q[4]
        cz q[2], q[0]
    }
    skip 1
    { # start at cycle 159
        y90 q[3]
        ym90 q[1]
    }
    { # start at cycle 160
        cz q[3], q[1]
        ym90 q[5]
    }
    cz q[2], q[5]
    cz q[3], q[1]
    { # start at cycle 163
        y90 q[0]
        ym90 q[2]
    }
    { # start at cycle 164
        cz q[3], q[6]
        cz q[0], q[2]
    }
    skip 1
    { # start at cycle 166
        y90 q[1]
        ym90 q[3]
    }
    cz q[1], q[3]
    skip 1
    { # start at cycle 169
        y90 q[3]
        ym90 q[1]
    }
    cz q[3], q[1]
    ym90 q[0]
    { # start at cycle 172
        y90 q[1]
        y90 q[2]
    }
    { # start at cycle 173
        cz q[1], q[4]
        cz q[2], q[0]
    }
    skip 1
    { # start at cycle 175
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    y90 q[3]
    { # start at cycle 179
        x q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    skip 1
    { # start at cycle 182
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    skip 1
    y90 q[3]
    cz q[3], q[6]
    ym90 q[1]
    cz q[3], q[1]
    ym90 q[0]
    { # start at cycle 190
        cz q[3], q[0]
        x q[6]
    }
    y q[6]
    cz q[3], q[6]
    skip 1
    { # start at cycle 194
        y90 q[6]
        ym90 q[3]
    }
    cz q[6], q[3]
    skip 1
    { # start at cycle 197
        y90 q[3]
        ym90 q[6]
    }
    cz q[3], q[6]
    skip 1
    y90 q[6]
    cz q[6], q[4]
    skip 1
    { # start at cycle 203
        y90 q[0]
        y90 q[1]
        y90 q[4]
        y90 q[5]
    }
    { # start at cycle 204
        x q[1]
        x q[4]
        x q[5]
        x q[6]
    }
