version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 5

.aKernel
    { x q[0] | x q[1] }
    wait 7
    swap q[0],q[1]
    wait 15
    { cz q[0],q[2] | cz q[1],q[4] }
    wait 15
