version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 4

.aKernel
    prep_z q[0]
    wait 1
    i q[0]
    wait 1
    h q[0]
    wait 1
    x q[0]
    wait 1
    y q[0]
    wait 1
    z q[0]
    wait 1
    x90 q[0]
    wait 1
    y90 q[0]
    wait 1
    mx90 q[0]
    wait 1
    my90 q[0]
    wait 1
    s q[0]
    wait 1
    sdag q[0]
    wait 1
    t q[0]
    wait 1
    tdag q[0]
    wait 1
    rx q[0], 0.15
    wait 1
    ry q[0], 0.15
    wait 1
    rz q[0], 0.15
    wait 1
    cnot q[0],q[1]
    wait 3
    cz q[0],q[1]
    wait 3
    toffoli q[0],q[1],q[2]
    wait 3
    swap q[0],q[1]
    wait 3
    { measure q[0] | measure q[1] }
    wait 14
