# Generated by OpenQL 0.9.0 for program test_cnot_2N_targetcommute
version 1.2

pragma @ql.name("test_cnot_2N_targetcommute")


.aKernel
    { # start at cycle 0
        cnot q[0], q[3]
        cnot q[6], q[3]
        cnot q[1], q[3]
    }
    skip 3
    { # start at cycle 4
        t q[6]
        t q[1]
    }
    skip 2
    { # start at cycle 7
        z q[6]
        z q[1]
    }
    skip 1
    t q[1]
    skip 2
    z q[1]
    skip 1
