version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 16

.kernel_noncomms
    x q[3]
    move q[3],q[0]
    wait 8
    tmove q[0],q[4]
    wait 29
    cnot q[4],q[7]
    wait 4
    x q[7]
