version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 1

.akernel
    rz q[0], -3.141593
    ry q[0], -3.141593
    rz q[0], 3.141593
