# Generated by OpenQL 0.9.0 for program test_cnot_2R_targetcommute
version 1.2

pragma @ql.name("test_cnot_2R_targetcommute")


.aKernel
    { # start at cycle 0
        cnot q[0], q[3]
        cnot q[6], q[3]
        t q[6]
        z q[6]
        cnot q[1], q[3]
        t q[1]
        z q[1]
        t q[1]
        z q[1]
    }
    skip 3
