version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_7_ALAP
    prepz q[0]
    wait 1
    h q[0]
    wait 1
    { prepz q[2] | t q[0] }
    wait 1
    { prepz q[5] | h q[0] | h q[2] }
    wait 1
    { prepz q[1] | prepz q[3] | prepz q[4] | prepz q[6] | t q[0] | t q[2] | h q[5] }
    wait 1
    { measure q[0] | measure q[1] | measure q[2] | measure q[3] | measure q[4] | measure q[5] | measure q[6] }
    wait 1
