version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3

.kernel1
    x q[0]
    wait 1
    y q[0]
    wait 1
    z q[0]
    wait 1
    h q[0]
    wait 1
    i q[0]
    wait 1
    s q[0]
    wait 1
    t q[0]
    wait 1

.controlled_kernel1
    { cnot q[1],q[0] | h q[2] }
    wait 3
    sdag q[0]
    wait 1
    cnot q[1],q[0]
    wait 3
    s q[0]
    wait 1
    h q[0]
    wait 1
    cnot q[1],q[0]
    wait 3
    h q[0]
    wait 1
    s q[0]
    wait 1
    h q[0]
    wait 1
    t q[0]
    wait 1
    cnot q[1],q[0]
    wait 3
    tdag q[0]
    wait 1
    h q[0]
    wait 1
    sdag q[0]
    wait 1
    cnot q[0],q[1]
    wait 3
    tdag q[1]
    wait 1
    cnot q[0],q[1]
    wait 3
    { t q[1] | t q[0] }
    wait 1
    cnot q[1],q[0]
    wait 3
    { sdag q[1] | cnot q[0],q[2] }
    wait 3
    cnot q[2],q[1]
    wait 3
    { t q[1] | tdag q[2] }
    wait 1
    cnot q[0],q[1]
    wait 3
    { cnot q[0],q[2] | t q[1] }
    wait 3
    tdag q[2]
    wait 1
    cnot q[2],q[1]
    wait 3
    h q[1]
    wait 1
    t q[1]
    wait 1
    h q[1]
    wait 1
    cnot q[2],q[1]
    wait 3
    { tdag q[1] | t q[2] }
    wait 1
    cnot q[0],q[2]
    wait 3
    { cnot q[0],q[1] | t q[2] }
    wait 3
    tdag q[1]
    wait 1
    cnot q[2],q[1]
    wait 3
    { s q[1] | cnot q[0],q[2] }
    wait 3
    { cnot q[1],q[0] | h q[2] }
    wait 3
