version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_toffoli_pass
    { t q[0] | t q[1] }
    wait 1
    h q[5]
    cnot q[1],q[0]
    t q[5]
    wait 2
    cnot q[5],q[1]
    wait 3
    cnot q[0],q[5]
    tdag q[1]
    wait 2
    cnot q[0],q[1]
    wait 3
    { tdag q[1] | tdag q[5] }
    wait 2
    cnot q[5],q[1]
    tdag q[0]
    wait 2
    cnot q[0],q[5]
    wait 3
    cnot q[1],q[0]
    wait 3
    measure q[0], b[0]
    wait 14
    { h q[5] | cond(b[0]) t q[0] | cond(b[0]) t q[1] }
    wait 1
    cond(b[0]) h q[5]
    cond(b[0]) cnot q[1],q[0]
    cond(b[0]) t q[5]
    wait 2
    cond(b[0]) cnot q[5],q[1]
    wait 3
    cond(b[0]) cnot q[0],q[5]
    cond(b[0]) tdag q[1]
    wait 2
    cond(b[0]) cnot q[0],q[1]
    wait 3
    { cond(b[0]) tdag q[1] | cond(b[0]) tdag q[5] }
    wait 2
    cond(b[0]) cnot q[5],q[1]
    cond(b[0]) tdag q[0]
    wait 2
    cond(b[0]) cnot q[0],q[5]
    wait 3
    cond(b[0]) cnot q[1],q[0]
    wait 1
    cond(b[0]) h q[5]
    wait 1
    measure q[0], b[0]
    wait 14
    { cond(b[0]) t q[0] | cond(b[0]) t q[1] }
    wait 1
    cond(b[0]) h q[5]
    cond(b[0]) cnot q[1],q[0]
    cond(b[0]) t q[5]
    wait 2
    cond(b[0]) cnot q[5],q[1]
    wait 3
    cond(b[0]) cnot q[0],q[5]
    cond(b[0]) tdag q[1]
    wait 2
    cond(b[0]) cnot q[0],q[1]
    wait 3
    { cond(b[0]) tdag q[1] | cond(b[0]) tdag q[5] }
    wait 2
    cond(b[0]) cnot q[5],q[1]
    cond(b[0]) tdag q[0]
    wait 2
    cond(b[0]) cnot q[0],q[5]
    wait 3
    cond(b[0]) cnot q[1],q[0]
    wait 1
    cond(b[0]) h q[5]
    wait 1
    measure q[0], b[0]
    wait 14
    { cond(b[0]) t q[0] | cond(b[0]) t q[1] }
    wait 1
    cond(b[0]) h q[5]
    cond(b[0]) cnot q[1],q[0]
    cond(b[0]) t q[5]
    wait 2
    cond(b[0]) cnot q[5],q[1]
    wait 3
    cond(b[0]) cnot q[0],q[5]
    cond(b[0]) tdag q[1]
    wait 2
    cond(b[0]) cnot q[0],q[1]
    wait 3
    { cond(b[0]) tdag q[1] | cond(b[0]) tdag q[5] }
    wait 2
    cond(b[0]) cnot q[5],q[1]
    cond(b[0]) tdag q[0]
    wait 2
    cond(b[0]) cnot q[0],q[5]
    wait 3
    cond(b[0]) cnot q[1],q[0]
    wait 1
    cond(b[0]) h q[5]
    wait 1
