version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    { cnot q[3],q[0] | cnot q[3],q[6] | x45 q[6] | x q[6] | cnot q[3],q[1] | x45 q[1] | x q[1] | x45 q[1] | x q[1] }
    wait 3
