version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 4

.aKernel
    prep_z q[0]
    i q[0]
    h q[0]
    x q[0]
    y q[0]
    z q[0]
    x90 q[0]
    y90 q[0]
    mx90 q[0]
    my90 q[0]
    s q[0]
    sdag q[0]
    t q[0]
    tdag q[0]
    rx q[0], 0.15
    ry q[0], 0.15
    rz q[0], 0.15
    cnot q[0],q[1]
    cz q[0],q[1]
    toffoli q[0],q[1],q[2]
    swap q[0],q[1]
    measure q[0]
    measure q[1]
