version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    cnot q[3],q[5]
    wait 3
    { cnot q[3],q[1] | t q[5] }
    wait 2
    y q[5]
    { cnot q[3],q[6] | t q[1] | t q[5] }
    wait 2
    { y q[1] | y q[5] }
    { cnot q[3],q[0] | t q[6] | t q[1] | t q[5] }
    wait 2
    { y q[6] | y q[1] | y q[5] }
