version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    { x q[3] | x45 q[3] | x q[0] | x45 q[0] }
    cnot q[3],q[0]
    wait 3
