version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 8

.kernel_maxcut
    red q[5],q[6]
    wait 3
    blue q[6],q[7]
    red q[3],q[5]
    wait 1
    blue q[4],q[7]
    wait 1
    { blue q[3],q[0] | x q[6] }
    swap q[7],q[6]
    { move_init q[2] | x q[5] }
    { move q[4],q[2] | swap q[0],q[3] | swap q[5],q[6] }
    move_init q[1]
    { move q[2],q[1] | red q[3],q[5] }
    wait 1
    swap q[0],q[1]
    wait 1
    blue q[3],q[0]
    wait 2
    blue q[1],q[0]
    wait 2
    { x q[0] | x q[1] | x q[3] | x q[5] }
