# Generated by OpenQL 0.9.0 for program test_edge_available
version 1.2

pragma @ql.name("test_edge_available")


.aKernel
    { # start at cycle 0
        cz q[0], q[2]
        cz q[4], q[6]
    }
    skip 3
