# Generated by OpenQL 0.9.0 for program test_cnot_2R_noncommute_DAR
version 1.2

pragma @ql.name("test_cnot_2R_noncommute_DAR")


.aKernel
    cnot q[3], q[5]
    skip 3
    cnot q[0], q[3]
    skip 3
    { # start at cycle 8
        x45 q[0]
        x q[0]
        x45 q[0]
    }
