version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    { prepz q[0] | prepz q[1] | prepz q[2] | prepz q[3] }
    wait 1
    { h q[0] | h q[1] | x q[2] | x q[3] }
    wait 1
    { measure q[0] | measure q[1] | measure q[2] | measure q[3] }
    wait 1
