version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_oneD4
    { x q[2] | ym90 q[0] }
    cz q[2],q[0]
    wait 1
    { y90 q[0] | x q[2] }
