# Generated by OpenQL 0.9.0 for program test_mapper_lingling5
version 1.2

pragma @ql.name("test_mapper_lingling5")


.kernel_lingling5
    { # start at cycle 0
        prepz q[5]
        prepz q[6]
    }
    skip 1
    prepz q[2]
    skip 28
    x q[5]
    y q[5]
    cz q[2], q[5]
    skip 1
    { # start at cycle 35
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 38
        y90 q[2]
        ym90 q[0]
    }
    cz q[2], q[0]
    y q[3]
    { # start at cycle 41
        x q[2]
        cz q[0], q[3]
    }
    y q[2]
    cz q[5], q[2]
    skip 1
    y90 q[6]
    x q[6]
    cz q[6], q[2]
    skip 1
    cz q[6], q[2]
    skip 1
    { # start at cycle 51
        y90 q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    ym90 q[5]
    cz q[2], q[5]
    skip 1
    { # start at cycle 56
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    { # start at cycle 58
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 61
        y90 q[2]
        ym90 q[0]
    }
    cz q[2], q[0]
    skip 1
    ym90 q[5]
    cz q[2], q[5]
    skip 1
    y90 q[5]
    cz q[1], q[5]
    { # start at cycle 69
        y90 q[0]
        ym90 q[2]
    }
    cz q[0], q[2]
    skip 1
    x q[5]
    { # start at cycle 73
        y90 q[2]
        y q[5]
    }
    cz q[5], q[2]
    skip 1
    y90 q[5]
    x q[5]
    { # start at cycle 78
        measure q[6]
        measure q[5]
    }
    skip 14
    { # start at cycle 93
        prepz q[6]
        prepz q[5]
    }
    skip 30
    ym90 q[0]
    cz q[2], q[0]
    skip 1
    x q[6]
    { # start at cycle 128
        y90 q[2]
        y q[6]
    }
    cz q[2], q[6]
    skip 1
    y90 q[5]
    { # start at cycle 132
        x q[5]
        ym90 q[1]
    }
    cz q[5], q[1]
    skip 1
    x q[5]
    y q[5]
    cz q[2], q[5]
    skip 1
    { # start at cycle 139
        y90 q[6]
        ym90 q[2]
    }
    cz q[6], q[2]
    skip 1
    y90 q[2]
    cz q[2], q[5]
    skip 1
    cz q[2], q[5]
    skip 1
    ym90 q[6]
    cz q[2], q[6]
    skip 1
    measure q[2]
    skip 14
    prepz q[2]
    skip 30
    y90 q[2]
    x q[2]
    cz q[2], q[0]
    skip 1
    { # start at cycle 200
        y90 q[0]
        ym90 q[2]
    }
    cz q[0], q[2]
    skip 1
    y90 q[2]
    cz q[2], q[5]
    skip 1
    x q[5]
    { # start at cycle 207
        y q[5]
        ym90 q[1]
    }
    cz q[5], q[1]
    skip 1
    { # start at cycle 210
        y90 q[1]
        ym90 q[5]
    }
    cz q[1], q[5]
    skip 1
    { # start at cycle 213
        y90 q[5]
        ym90 q[1]
    }
    cz q[5], q[1]
    skip 1
    { # start at cycle 216
        y90 q[1]
        ym90 q[4]
    }
    cz q[1], q[4]
    skip 1
    y90 q[1]
    x q[1]
    measure q[1]
    skip 14
    prepz q[1]
    skip 27
    ym90 q[0]
    cz q[2], q[0]
    skip 1
    y q[2]
    cz q[5], q[2]
    skip 1
    { # start at cycle 270
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    skip 1
    { # start at cycle 273
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    y90 q[2]
    cz q[2], q[0]
    skip 1
    { # start at cycle 279
        y90 q[0]
        ym90 q[2]
    }
    cz q[0], q[2]
    skip 1
    { # start at cycle 282
        y90 q[2]
        ym90 q[0]
    }
    { # start at cycle 283
        y90 q[1]
        cz q[2], q[0]
    }
    x q[1]
    cz q[1], q[5]
    skip 1
    { # start at cycle 287
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 290
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    x q[1]
    { # start at cycle 293
        y q[1]
        y90 q[5]
    }
    cz q[5], q[1]
    skip 1
    cz q[5], q[1]
    ym90 q[2]
    cz q[5], q[2]
    skip 1
    measure q[5]
    skip 14
    prepz q[5]
    skip 29
    y90 q[2]
    cz q[2], q[6]
    skip 1
    { # start at cycle 348
        y90 q[6]
        ym90 q[2]
    }
    cz q[6], q[2]
    skip 1
    { # start at cycle 351
        y90 q[2]
        ym90 q[6]
    }
    cz q[2], q[6]
    skip 1
    y90 q[0]
    { # start at cycle 355
        y90 q[5]
        cz q[0], q[3]
    }
    { # start at cycle 356
        x q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 359
        y90 q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    { # start at cycle 361
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    skip 1
    { # start at cycle 364
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    { # start at cycle 366
        y90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 369
        y90 q[2]
        ym90 q[0]
    }
    cz q[2], q[0]
    skip 1
    { # start at cycle 372
        y90 q[0]
        ym90 q[2]
    }
    cz q[0], q[2]
    y90 q[4]
    cz q[5], q[1]
    { # start at cycle 376
        y90 q[2]
        ym90 q[0]
    }
    { # start at cycle 377
        cz q[4], q[1]
        cz q[2], q[0]
    }
    skip 1
    { # start at cycle 379
        ym90 q[5]
        ym90 q[2]
    }
    cz q[5], q[2]
    skip 1
    { # start at cycle 382
        y90 q[2]
        ym90 q[5]
    }
    cz q[2], q[5]
    x q[1]
    { # start at cycle 385
        y90 q[5]
        y q[1]
    }
    cz q[1], q[5]
    skip 1
    y90 q[1]
    x q[1]
    measure q[1]
    skip 14
    prepz q[1]
    skip 30
    ym90 q[2]
    { # start at cycle 437
        cz q[5], q[2]
        y90 q[1]
    }
    x q[1]
    cz q[1], q[5]
    skip 1
    { # start at cycle 441
        y90 q[5]
        ym90 q[1]
    }
    cz q[5], q[1]
    skip 1
    { # start at cycle 444
        y90 q[1]
        ym90 q[5]
    }
    cz q[1], q[5]
    skip 1
    { # start at cycle 447
        y90 q[5]
        y90 q[2]
    }
    cz q[5], q[2]
    skip 1
    y90 q[2]
    cz q[2], q[0]
    skip 1
    { # start at cycle 453
        y90 q[0]
        ym90 q[2]
    }
    cz q[0], q[2]
    skip 1
    x q[5]
    { # start at cycle 457
        y q[5]
        y90 q[2]
    }
    cz q[2], q[5]
    skip 1
    cz q[2], q[5]
    skip 1
    ym90 q[0]
    cz q[2], q[0]
    skip 1
    measure q[2]
    skip 2
    y90 q[0]
    cz q[0], q[3]
    ym90 q[4]
    cz q[1], q[4]
    { # start at cycle 472
        y90 q[3]
        ym90 q[0]
    }
    cz q[3], q[0]
    skip 1
    cz q[1], q[5]
    { # start at cycle 476
        y90 q[0]
        ym90 q[3]
    }
    cz q[0], q[3]
    { # start at cycle 478
        y90 q[4]
        ym90 q[1]
    }
    { # start at cycle 479
        cz q[4], q[1]
        ym90 q[0]
    }
    cz q[2], q[0]
    y90 q[1]
    cz q[1], q[5]
    { # start at cycle 483
        y90 q[0]
        ym90 q[2]
    }
    cz q[0], q[2]
    skip 1
    x q[5]
    { # start at cycle 487
        y90 q[2]
        y q[5]
    }
    cz q[5], q[2]
    skip 1
    y90 q[5]
    x q[5]
    measure q[5]
    skip 10
    { # start at cycle 503
        ym90 q[4]
        ym90 q[0]
    }
    { # start at cycle 504
        cz q[1], q[4]
        cz q[2], q[0]
    }
    skip 1
    { # start at cycle 506
        y90 q[0]
        y90 q[2]
        y90 q[3]
        y90 q[4]
        y90 q[6]
    }
