# Generated by OpenQL 0.9.0 for program test_barrier_all
version 1.2

pragma @ql.name("test_barrier_all")


.aKernel
    ry90 q[2]
    skip 1
    { # start at cycle 2
        ry90 q[0]
        rx90 q[2]
    }
    skip 1
    { # start at cycle 4
        measure q[0]
        measure q[1]
        measure q[2]
        measure q[4]
    }
    skip 1
    { # start at cycle 6
        barrier q[0], q[1], q[2], q[3], q[4], q[5], q[6]
        ry90 q[4]
        ry90 q[1]
    }
    skip 1
    { # start at cycle 8
        measure q[0]
        measure q[1]
        measure q[2]
        measure q[4]
    }
    skip 1
    { # start at cycle 10
        barrier q[0], q[1], q[2], q[3], q[4], q[5], q[6]
        ry90 q[4]
        ry90 q[1]
    }
    skip 1
