version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 4

.aKernel
    x q[0]
    wait 7
    swap q[0],q[1]
    wait 15
    x q[0]
    wait 7
