version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 2

.akernel
    rz q[0], -1.570796
    ry q[0], -1.570796
    rz q[0], 1.570796
    rz q[1], 1.570796
    cnot q[0],q[1]
    rz q[1], -3.141593
    cnot q[0],q[1]
    rz q[0], -1.570796
    ry q[0], -3.141593
    rz q[0], 0.000000
