# Generated by OpenQL 0.9.0 for program test_smit
version 1.2

pragma @ql.name("test_smit")


.aKernel
    { # start at cycle 0
        prepz q[0]
        prepz q[1]
        prepz q[2]
        prepz q[3]
        ym90 q[4]
    }
    skip 1
    { # start at cycle 2
        h q[0]
        h q[1]
        x q[2]
        x q[3]
    }
    skip 1
    { # start at cycle 4
        ym90 q[0]
        cz q[1], q[4]
        measure q[3]
    }
    skip 1
    cz q[2], q[0]
    skip 1
    { # start at cycle 8
        ry90 q[4]
        measure q[1]
    }
    skip 1
    ry90 q[0]
    skip 1
    ym90 q[0]
    skip 1
    cz q[2], q[0]
    skip 3
    { # start at cycle 18
        ry90 q[0]
        measure q[2]
    }
    skip 1
    measure q[0]
    skip 1
