version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.aKernel
    t q[0]
    wait 2
    z q[0]
    wait 1
    cnot q[3],q[0]
    wait 3
    t q[3]
    wait 2
    z q[3]
    wait 1
