# Generated by OpenQL 0.9.0 for program test_multi_controlled
version 1.2

pragma @ql.name("test_multi_controlled")


.kernel1
    x q[0]
    skip 1
    cnot q[0], q[1]
    skip 3

.controlled_kernel1
    toffoli q[2], q[3], q[7]
    skip 7
    toffoli q[4], q[7], q[8]
    skip 7
    toffoli q[5], q[8], q[9]
    skip 7
    toffoli q[6], q[9], q[10]
    skip 7
    cnot q[10], q[0]
    skip 3
    toffoli q[0], q[10], q[1]
    skip 7
    toffoli q[6], q[9], q[10]
    skip 7
    toffoli q[5], q[8], q[9]
    skip 7
    toffoli q[4], q[7], q[8]
    skip 7
    toffoli q[2], q[3], q[7]
    skip 7
