# Generated by OpenQL 0.10.5 for program test_rOEE
version 1.2

pragma @ql.name("test_rOEE")


.kernel_rOEE
    { # start at cycle 0
        x q[0]
        x q[1]
        x q[4]
        x q[5]
    }
    { # start at cycle 1
        cnot q[0], q[1]
        cnot q[4], q[5]
    }
    skip 3
    { # start at cycle 5
        x q[8]
        x q[9]
    }
    { # start at cycle 6
        cnot q[8], q[9]
        cnot q[0], q[4]
        cnot q[1], q[5]
        cnot q[2], q[6]
        cnot q[3], q[7]
    }
    skip 3
    { # start at cycle 10
        x q[12]
        x q[13]
    }
    { # start at cycle 11
        cnot q[12], q[13]
        cnot q[0], q[8]
        cnot q[1], q[9]
        cnot q[2], q[10]
        cnot q[3], q[11]
    }
    skip 4
    { # start at cycle 16
        cnot q[0], q[12]
        cnot q[1], q[13]
        cnot q[2], q[14]
        cnot q[3], q[15]
    }
    skip 4
    { # start at cycle 21
        cnot q[4], q[0]
        cnot q[5], q[1]
        cnot q[6], q[2]
        cnot q[7], q[3]
    }
    skip 4
    { # start at cycle 26
        cnot q[4], q[8]
        cnot q[5], q[9]
        cnot q[6], q[10]
        cnot q[7], q[11]
    }
    skip 4
    { # start at cycle 31
        cnot q[4], q[12]
        cnot q[5], q[13]
        cnot q[6], q[14]
        cnot q[7], q[15]
        cnot q[8], q[0]
        cnot q[9], q[1]
        cnot q[10], q[2]
        cnot q[11], q[3]
    }
    skip 4
    { # start at cycle 36
        cnot q[8], q[4]
        cnot q[9], q[5]
        cnot q[10], q[6]
        cnot q[11], q[7]
    }
    skip 4
    { # start at cycle 41
        cnot q[8], q[12]
        cnot q[9], q[13]
        cnot q[10], q[14]
        cnot q[11], q[15]
    }
    skip 4
    { # start at cycle 46
        cnot q[12], q[0]
        cnot q[13], q[1]
        cnot q[14], q[2]
        cnot q[15], q[3]
    }
    skip 4
    { # start at cycle 51
        cnot q[12], q[4]
        cnot q[13], q[5]
        cnot q[14], q[6]
        cnot q[15], q[7]
    }
    skip 4
    { # start at cycle 56
        cnot q[12], q[8]
        cnot q[13], q[9]
        cnot q[14], q[10]
        cnot q[15], q[11]
    }
    skip 4
