version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.kernel_all
    { x q[0] | x q[3] }
    cz_park q[0],q[3],q[2]
    wait 1
    cz_park q[3],q[0],q[2]
    wait 1
    { x q[2] | x q[1] | x q[4] | x q[5] | x q[6] }
    { cz_park q[1],q[3],q[4] | cz q[2],q[5] | cz q[4],q[6] }
    wait 1
    { cz_park q[3],q[1],q[4] | cz q[5],q[2] | cz q[6],q[4] }
    wait 1
    cz_park q[3],q[5],q[6]
    wait 1
    cz_park q[5],q[3],q[6]
    wait 1
    { cz_park q[0],q[2],q[3] | cz_park q[1],q[4],q[3] | cz_park q[3],q[6],q[5] }
    wait 1
    { cz_park q[2],q[0],q[3] | cz_park q[4],q[1],q[3] | cz_park q[6],q[3],q[5] }
    wait 1
    { x q[0] | x q[1] | x q[2] | x q[3] | x q[4] | x q[5] | x q[6] }
