IF(UNIX)
    SET(LEMON_ROOT_DIR "/opt/lemon" CACHE PATH "LEMON root directory")
ELSE(UNIX)
    SET(LEMON_ROOT_DIR "C:/Program Files/LEMON" CACHE PATH "LEMON root directory")
ENDIF(UNIX)


FIND_PATH(LEMON_INCLUDE_DIR
  lemon/core.h
  HINTS ${LEMON_ROOT_DIR}/include
        "C:/Program Files/LEMON/include"
        
)

FIND_LIBRARY(LEMON_LIBRARY
  NAMES lemon emon
  HINTS ${LEMON_ROOT_DIR}/lib
        "C:/Program Files/LEMON/lib" 
        
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LEMON DEFAULT_MSG LEMON_LIBRARY LEMON_INCLUDE_DIR)

IF(LEMON_FOUND)
  SET(LEMON_INCLUDE_DIRS ${LEMON_INCLUDE_DIR})
  SET(LEMON_LIBRARIES ${LEMON_LIBRARY})
ENDIF(LEMON_FOUND)

MARK_AS_ADVANCED(LEMON_LIBRARY LEMON_INCLUDE_DIR)